/* Copyright (c) 2022 Toriti Tech Team https://t.me/ToritiTech */

module.exports = {
  APP_USER_ERROR: {
    STARTWORK_BEFORE_FINISHWORK: 'STARTWORK_BEFORE_FINISHWORK',
    CAN_NOT_FIND_APP_USER_RECORD: 'CAN_NOT_FIND_APP_USER_RECORD',
    CAN_NOT_FIND_STATION_RECORD: 'CAN_NOT_FIND_STATION_RECORD',
    NO_DATA: 'NO_DATA',
  },
};
