/* Copyright (c) 2022 Toriti Tech Team https://t.me/ToritiTech */

'use strict';
//This model is use to display info of Stations in public.
//BEWARE !! DO NOT SEND INFO THAT RELATED TO SYSTEM INSIDE MODEL
const Joi = require('joi');

const rawRealEstateSchema = Joi.object({
  AreaCountryName: Joi.string(),
  AreaStateName: Joi.string(),
  AreaProvinceName: Joi.string(),
  AreaCityName: Joi.string(),
  AreaDistrictName: Joi.string(),
  AreaWardName: Joi.string(),
  AreaTypeName: Joi.string(),
  LocationHomeNumber: Joi.string(),
  LocationFullAddress: Joi.string(),
  LocationStreetName: Joi.string(),
  LocationStreetWidth: Joi.number(),
  LocationPositionName: Joi.string(),
  LocationFrontStreetWidth: Joi.number(),
  LocationDistanceToCityCenter: Joi.string(),
  LocationTunel: Joi.string(),
  LocationProjectName: Joi.string(),
  LocationMapLong: Joi.string(),
  LocationMapLat: Joi.string(),
  LandWidth: Joi.number(),
  LandLong: Joi.number(),
  LandDefaultSquare: Joi.number(),
  LandRealitySquare: Joi.number(),
  LandRoadSquare: Joi.number(),
  LandRealConstructionSquare: Joi.number(),
  LandFrontWidth: Joi.number(),
  LandFrontSides: Joi.string(),
  LandShapeName: Joi.string(),
  LandPlanningTypeName: Joi.string(),
  LandAgricultureSquare: Joi.string(),
  LandDirectionName: Joi.string(),
  HouseConstructionSquare: Joi.string(),
  HouseFloorsSquare: Joi.string(),
  HouseFloors: Joi.number(),
  HouseLivingRooms: Joi.string(),
  HouseKitchens: Joi.string(),
  HouseBedRooms: Joi.number(),
  HouseToilets: Joi.number(),
  HouseTerrace: Joi.string(),
  HouseFrontYard: Joi.string(),
  HouseBackYard: Joi.string(),
  HouseGarage: Joi.string(),
  HousePool: Joi.string(),
  HouseBasement: Joi.string(),
  HouseMiddleFloors: Joi.string(),
  HouseStairType: Joi.string(),
  HouseWallType: Joi.string(),
  HouseFloorsType: Joi.string(),
  HouseRoofType: Joi.string(),
  HouseCompleteName: Joi.string(),
  HouseFurnitureName: Joi.string(),
  HouseFurnitureList: Joi.string(),
  HouseQualityName: Joi.string(),
  HouseElectricity: Joi.string(),
  HouseWater: Joi.string(),
  HouseConstructionHeight: Joi.string(),
  HouseAbilites: Joi.string(),
  HouseNearbyPlace: Joi.string(),
  ValueSalePrice: Joi.number(),
  ValueSaleUnitPrice: Joi.number(),
  ValueDiscussPrice: Joi.string(),
  ValueLandUnitPrice: Joi.string(),
  ValueHouseUnitPrice: Joi.string(),
  ValueHousePrice: Joi.string(),
  ValueLandPrice: Joi.string(),
  ValueRentPrice: Joi.string(),
  ValueRentUnitPrice: Joi.string(),
  JuridicalName: Joi.number(),
  JuridicalPaperCode: Joi.string(),
  JuridicalLandCode: Joi.string(),
  JuridicalLandSquare: Joi.string(),
  JuridicalConstructionSquare: Joi.string(),
  JuridicalMainConstruction: Joi.string(),
  JuridicalOtherObject: Joi.string(),
  JuridicalFloorSquare: Joi.string(),
  JuridicalSubConstructions: Joi.string(),
  JuridicalLatest: Joi.string(),
  JuridicalUpdates: Joi.string(),
  JuridicalContructionLimitation: Joi.string(),
  JuridicalStatusName: Joi.string(),
  JuridicalUsingStatusName: Joi.string(),
  ImagesHouse: Joi.array().items(Joi.string()),
  ImagesNearBy: Joi.array().items(Joi.string()),
  ImagesInside: Joi.array().items(Joi.string()),
  ImagesV360Inside: Joi.array().items(Joi.string()),
  ImagesV360Outside: Joi.array().items(Joi.string()),
  ImagesDroneOutSide: Joi.array().items(Joi.string()),
  ImagesDroneNearby: Joi.array().items(Joi.string()),
  ImagesJuridical: Joi.array().items(Joi.string()),
  ImagesPlanRoadSquare: Joi.array().items(Joi.string()),
  ImagesPlanUsage: Joi.array().items(Joi.string()),
  ContactTypeName: Joi.string(),
  ContactName: Joi.string(),
  ContactAge: Joi.string(),
  ContactDob: Joi.string(),
  ContactGender: Joi.string(),
  ContactPhone: Joi.string(),
  ContactAddress: Joi.string(),
  ContactIdentity: Joi.string(),
  ContactFacebook: Joi.string(),
  ContactTwitter: Joi.string(),
  ContactTelegram: Joi.string(),
  ContactZalo: Joi.string(),
  ContactGoogle: Joi.string(),
  ContactApple: Joi.string(),
  ContactPosition: Joi.string(),
  ContactDomain: Joi.string(),
  ContactJob: Joi.string(),
  ContactCompany: Joi.string(),
  ContactEmail: Joi.string(),
  PlanRentPrice: Joi.string(),
  PlanRentUnitPrice: Joi.string(),
  Plan6mSalePrice: Joi.string(),
  Plan3mSalePrice: Joi.string(),
  Plan1ySalePrice: Joi.string(),
  Plan5ySalePrice: Joi.string(),
  PlanEvaluation: Joi.string(),
  PlanProfitPercentage: Joi.string(),
  PlanLoanPercentage: Joi.string(),
  PlanLoanMaximum: Joi.string(),
  PlanLoanPayRateMonthly: Joi.string(),
  PlanLoanTime: Joi.string(),
  PlanInvestmentTypeName: Joi.string(),
  PlanInvestmentRankingName: Joi.string(),
  PlanInvestmentPoints: Joi.string(),
  ContactAnalysisOwnerReason: Joi.string(),
  ContactAnalysisOwnerConfident: Joi.string(),
  ContactAnalysisBrokerReason: Joi.string(),
  ContactAnalysisBrokerConfident: Joi.string(),
  RecordAnalysisFakeReasons: Joi.string(),
  RecordAnalysisFakeConfident: Joi.string(),
  SystemModifierName: Joi.string(),
  SystemCreatorName: Joi.string(),
  SystemInfomationRankingName: Joi.string(),
  SystemInfoConfirmStatusName: Joi.string(),
  SystemInfoUsingStatusName: Joi.string(),
  SystemInfoVisibleStatus: Joi.string(),
  SystemInfoSecurityLevelName: Joi.string(),
  SystemSourceName: Joi.string(),
  SystemSourceType: Joi.string(),
  SystemPostType: Joi.string(),
  SystemPostUrl: Joi.string(),
  SystemSourceLink: Joi.string(),
  SystemCrawlingStatus: Joi.string(),
  SystemDateOfPost: Joi.string(),
  SystemLastActiveDate: Joi.string(),
  SystemNote: Joi.string(),
  SystemCollectionPoints: Joi.string(),
  SystemRecordType: Joi.string(),
  SystemRecordTitle: Joi.string(),
  SystemRecordContent: Joi.string(),
  SystemViewCount: Joi.string(),
  SystemViewerName: Joi.string(),
  SystemAnalysisLevel: Joi.string(),
  Comments: Joi.string(),
  ChangedActivities: Joi.string(),
}).unknown(true);

function fromData(data) {
  let modelData = {
    ...data,
  };

  let outputModel = rawRealEstateSchema.validate(modelData);
  if (outputModel.error === undefined || outputModel.error === null || outputModel.error === '') {
    return outputModel.value;
  } else {
    console.error(outputModel.error);
    return undefined;
  }
}

module.exports = {
  fromData,
  schema: rawRealEstateSchema,
};
